/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Leonardo Aguilar
 */
public class Registro extends javax.swing.JFrame {

    static List<Producto> productos = new ArrayList<Producto>();
    
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        grupoTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtunidad = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProductos = new javax.swing.JList<>();
        irventa = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comestible = new javax.swing.JRadioButton();
        utensilio = new javax.swing.JRadioButton();
        oficina = new javax.swing.JRadioButton();
        industrial = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(515, 450));
        setMinimumSize(new java.awt.Dimension(515, 450));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Registro de Productos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(29, 23, 160, 22);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(29, 72, 60, 14);

        jLabel3.setText("Unidad de medida");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(29, 217, 110, 14);

        jLabel4.setText("Cantidad");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(29, 259, 60, 14);

        jLabel5.setText("Precio");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(29, 287, 40, 14);
        getContentPane().add(txtnombre);
        txtnombre.setBounds(139, 69, 80, 20);
        getContentPane().add(txtunidad);
        txtunidad.setBounds(139, 214, 80, 20);
        getContentPane().add(txtcantidad);
        txtcantidad.setBounds(140, 253, 80, 20);

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });
        getContentPane().add(txtprecio);
        txtprecio.setBounds(139, 284, 81, 20);

        jLabel6.setText("$");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(129, 287, 6, 14);

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar);
        guardar.setBounds(64, 332, 80, 23);

        jScrollPane1.setViewportView(listProductos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(269, 69, 201, 223);

        irventa.setText("Ir a Venta");
        irventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irventaActionPerformed(evt);
            }
        });
        getContentPane().add(irventa);
        irventa.setBounds(153, 332, 81, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("Producto");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(269, 50, 50, 13);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("Cantidad");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(329, 50, 50, 13);

        grupoTipo.add(comestible);
        comestible.setText("Comestible");
        comestible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comestibleActionPerformed(evt);
            }
        });
        getContentPane().add(comestible);
        comestible.setBounds(142, 107, 90, 23);

        grupoTipo.add(utensilio);
        utensilio.setText("Utensilio");
        getContentPane().add(utensilio);
        utensilio.setBounds(142, 130, 90, 23);

        grupoTipo.add(oficina);
        oficina.setText("Oficina");
        oficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oficinaActionPerformed(evt);
            }
        });
        getContentPane().add(oficina);
        oficina.setBounds(142, 153, 90, 23);

        grupoTipo.add(industrial);
        industrial.setText("Industrial");
        getContentPane().add(industrial);
        industrial.setBounds(142, 176, 90, 23);

        jLabel9.setText("Tipo:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(29, 111, 40, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("Tipo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 49, 30, 13);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(252, 332, 53, 23);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/colorf.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-10, -10, 510, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        String nombre = txtnombre.getText();
        String unidad = txtunidad.getText();
        int cantidad = Integer.parseInt(txtcantidad.getText());
        double precio = Double.parseDouble(txtprecio.getText());
        String tipo = "";
        if(comestible.isSelected()){
            tipo = "Comestible";
        }else if(utensilio.isSelected()){
            tipo = "Utensilio";
        }else if(oficina.isSelected()){
            tipo = "Oficina";
        }else if(industrial.isSelected()){
            tipo = "Industrial";
        }
        // creamos objeto
        Producto producto = new Producto(nombre, tipo, unidad, cantidad, precio);
        // agregamos el producto a nuestra lista de productos
        productos.add(producto);
        visualizar_productos_en_la_lista();
        limpiar();
    }//GEN-LAST:event_guardarActionPerformed

    private void irventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irventaActionPerformed
        // TODO add your handling code here:
        Venta objVenta = new Venta();
        objVenta.show();
    }//GEN-LAST:event_irventaActionPerformed

    private void oficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oficinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oficinaActionPerformed

    private void comestibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comestibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comestibleActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    public void visualizar_productos_en_la_lista() {
        String[] prodNombres = new String[productos.size()];
        //recorrer los productos de la lista productos
        int i = 0;
        for (Producto producto : productos) {
            prodNombres[i] = producto.getNombre() +"          "+ 
                    producto.getCantidad()+"         "+ producto.getTipo();
            i++;
        }
        listProductos.setListData(prodNombres);
    }

    public void limpiar() {
        txtnombre.setText("");
        txtunidad.setText("");
        txtcantidad.setText("");
        txtprecio.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JRadioButton comestible;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JButton guardar;
    private javax.swing.JRadioButton industrial;
    private javax.swing.JButton irventa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listProductos;
    private javax.swing.JRadioButton oficina;
    private javax.swing.JButton salir;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtunidad;
    private javax.swing.JRadioButton utensilio;
    // End of variables declaration//GEN-END:variables
}
