/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;
import puntodeventa.Registro;
/**
 *
 * @author Leonardo Aguilar
 */
public class Venta extends javax.swing.JFrame {
    int i = 0;
    String[] prod = new String[10];
    double sub = 0;
    
    /**
     * Creates new form Venta
     */
    public Venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cont = new javax.swing.JSpinner();
        generar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        mens = new javax.swing.JLabel();
        lblsub = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFactura = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbliva = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 550));
        setMinimumSize(new java.awt.Dimension(450, 550));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Punto de Venta");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 11, 120, 24);

        jLabel2.setText("Ingrese nombre del producto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(31, 41, 160, 29);

        txtbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(txtbusqueda);
        txtbusqueda.setBounds(197, 45, 101, 20);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(316, 44, 70, 23);

        jLabel3.setText("Nombre Producto");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 96, 100, 14);

        jLabel4.setText("Stock");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(124, 96, 40, 14);

        jLabel5.setText("Precio");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(178, 96, 40, 14);

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblNombre);
        lblNombre.setBounds(10, 116, 104, 14);

        lblCantidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblCantidad);
        lblCantidad.setBounds(124, 116, 37, 14);

        lblPrecio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(lblPrecio);
        lblPrecio.setBounds(178, 116, 49, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("$");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(171, 116, 7, 14);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(20, 462, 53, 23);

        jLabel6.setText("Unidades a comprar:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(227, 111, 120, 14);
        getContentPane().add(cont);
        cont.setBounds(344, 108, 60, 30);

        generar.setText("Generar Factura");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });
        getContentPane().add(generar);
        generar.setBounds(95, 141, 120, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Pre Factura");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 195, 65, 14);
        getContentPane().add(mens);
        mens.setBounds(216, 141, 188, 23);

        lblsub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lblsub);
        lblsub.setBounds(306, 394, 56, 14);

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar);
        agregar.setBounds(18, 141, 71, 23);

        jLabel11.setText("IVA:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(266, 414, 30, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("$");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(293, 414, 7, 14);

        jLabel12.setText("Total:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(260, 434, 40, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("$");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(294, 434, 7, 14);
        getContentPane().add(lbltotal);
        lbltotal.setBounds(307, 434, 55, 14);

        jLabel8.setText("Nombre");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 220, 50, 14);

        jLabel14.setText("Precio U");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(118, 220, 50, 14);

        jLabel15.setText("Cantidad");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(206, 220, 50, 14);

        jLabel16.setText("Importe");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(286, 220, 50, 14);

        jScrollPane1.setViewportView(listFactura);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 240, 353, 148);

        jLabel17.setText("Sub Total:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(238, 394, 60, 14);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("$");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(293, 394, 7, 14);
        getContentPane().add(lbliva);
        lbliva.setBounds(306, 414, 56, 14);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/colorf.jpg"))); // NOI18N
        jLabel19.setMaximumSize(new java.awt.Dimension(500, 650));
        jLabel19.setMinimumSize(new java.awt.Dimension(500, 650));
        jLabel19.setPreferredSize(new java.awt.Dimension(500, 650));
        getContentPane().add(jLabel19);
        jLabel19.setBounds(-10, -10, 460, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusquedaActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        String nombreBuscar = txtbusqueda.getText();
        lblNombre.setText("No Existe...");
        lblCantidad.setText("");
        lblPrecio.setText("");
        for(Producto p : Registro.productos){
            if(p.getNombre().contains(nombreBuscar)){
                lblNombre.setText(p.getNombre());
                lblCantidad.setText(String.valueOf(p.getCantidad()));
                lblPrecio.setText(String.valueOf(p.getPrecio()));
            }
        }
        
        mens.setText("");
        lblsub.setText("");
    }//GEN-LAST:event_buscarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        // TODO add your handling code here:
        
        listFactura.setListData(prod);
        double iva = sub * 0.12;
        double total = sub + iva;
        
        lblsub.setText(String.valueOf(sub));
        lbliva.setText(String.valueOf(iva));
        lbltotal.setText(String.valueOf(total));
        
    }//GEN-LAST:event_generarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        String nombreBuscar = txtbusqueda.getText();
       
        for(Producto producto : Registro.productos){
            if(producto.getNombre().contains(nombreBuscar) ){
                if(producto.getCantidad()> Integer.parseInt(cont.getValue().toString())) {
                    prod[i] = producto.getNombre() +"                       " +
                        producto.getPrecio()  +  "                          " +
                        producto.getCantidad() +"                            " + 
                        Integer.parseInt(cont.getValue().toString()) *
                            producto.getPrecio();
                    i++;
                    sub = sub + (Integer.parseInt(cont.getValue().toString()) *
                        producto.getPrecio());
                    int aux = producto.getCantidad() - Integer.parseInt(cont.getValue().toString());
                    producto.setCantidad(aux);
                }else{
                mens.setText("No disponemos de tal cantidad en el stock");
                }
                
            }
            
        }
        
        
    }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscar;
    private javax.swing.JSpinner cont;
    private javax.swing.JButton generar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lbliva;
    private javax.swing.JLabel lblsub;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JList<String> listFactura;
    private javax.swing.JLabel mens;
    private javax.swing.JButton salir;
    private javax.swing.JTextField txtbusqueda;
    // End of variables declaration//GEN-END:variables
}
